# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default='c9ddf5e2-0477-4e6c-9bbb-19b2387adff1', editable=False, unique=True),
        ),
    ]
