# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20160109_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default='d062c7a3-7dc1-4e49-a2e5-192add49b038', editable=False),
        ),
    ]
