# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import eventex.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20160109_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default=eventex.subscriptions.models._createHash, editable=False, unique=True),
        ),
    ]
