# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='name',
            field=models.CharField(default='Grace Hopper', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo',
            field=models.URLField(default='http://hbn.link/hopper-pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='slug',
            field=models.SlugField(default='grace-hopper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='website',
            field=models.URLField(default='http://hbn.link/hopper-site'),
            preserve_default=False,
        ),
    ]
